services:
  selenium-hub4:
    image: selenium/hub:latest
    container_name: selenium-hub4
    ports:
      - "4441:4441"
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub4
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub4
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      
  chrome1:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub4
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub4
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome2:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub4
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub4
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome3:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub4
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub4
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443      
      
  chrome4:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub4
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub4
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  
  chrome5:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub4
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub4
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  
  real_device:
    image: appium/appium
    depends_on:
      - selenium-hub4
    network_mode: "service:selenium-hub4"
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
      - $PWD/example/sample_apk:/root/tmp
    environment:
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium-hub4
      - RELAXED_SECURITY=true
  
  nexus_7.1.1:
    image: oklabs/docker-android-x86-7.1.1:latest
    privileged: true
    scale: 1
    depends_on:
      - selenium-hub4
      - real_device
    ports:
      - 6080:6080
      - 4723:4723
      - 5554:5554
      - 5555:5555
    volumes:
      - $PWD/example/sample_apk:/root/tmp/sample_apk
      - ./video-nexus_7.1.1:/tmp/video
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium-hub4
      - AUTO_RECORD=true
