version: "3.8"
services:
  Android-Service:
    image: android-emulator
    build: .
    container_name: Android-Service
    ports:
      - "4725:4725"
    environment: 
      APPIUM_PORT: 4725
    privileged: true
    command: 
      bash -C './start_emuheaded.sh && ./start_appium.sh'
    tty: true
    stdin_open: true
    
    
